version: '3.1'

services:
  db:
    image: mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    volumes:
       - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_USER: admin
      MYSQL_DATABASE: flask