"""empty message

Revision ID: c47537fee517
Revises: 545b24f68887
Create Date: 2021-01-14 23:46:50.662554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47537fee517'
down_revision = '545b24f68887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_issue', sa.DATETIME(), nullable=True),
    sa.Column('result', sa.FLOAT(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_result')
    # ### end Alembic commands ###
